export const shopData = [
  {
    id: 1,
    imagePath: "AuthorPreserver",
    category: "T-Shirt",
    title: "Author Preserver",
    oldPrice: "5000",
    newPrice: "4500",
    description: "Oooooh-weeee, my first shirt post!",
    color: "black",
  },
  {
    id: 2,
    imagePath: "Blessed",
    category: "T-Shirt",
    title: "Blessed",
    oldPrice: "4500",
    newPrice: "4000",
    description: "Oooooh-weeee, my first shirt post!",
    color: "black",
  },
  {
    id: 3,
    imagePath: "FourthMan",
    category: "T-Shirt",
    title: "Fourth Man",
    oldPrice: "5000",
    newPrice: "4500",
    description: "Oooooh-weeee, my first shirt post!",
    color: "black",
  },
  {
    id: 4,
    imagePath: "jt",
    category: "T-Shirt",
    title: "Jesus & Therapy",
    oldPrice: "5000",
    newPrice: "4500",
    description: "Oooooh-weeee, my first shirt post!",
    color: "black",
  },
  {
    id: 5,
    imagePath: "JustGrace",
    category: "T-Shirt",
    title: "Just Grace",
    oldPrice: "5000",
    newPrice: "4500",
    description: "Oooooh-weeee, my first shirt post!",
    color: "black",
  },
  {
    id: 6,
    imagePath: "SkyDaddy",
    category: "T-Shirt",
    title: "Sky Daddy",
    oldPrice: "4500",
    newPrice: "4000",
    description: "Oooooh-weeee, my first shirt post!",
    color: "black",
  },
]
